"""Generate capital and US serviceable-demand scenario reports."""
from pathlib import Path
import pandas as pd
from copy import deepcopy
import json
from model_core import Params
from demand_model import DemandModel
from supply_model import SupplyModel

HERE = Path(__file__).resolve().parent


def main():
    out = HERE / "outputs"
    out.mkdir(exist_ok=True)
    demand = DemandModel.from_json(HERE / "demand_parameters.json")
    supply = SupplyModel.from_json(HERE / "parameters.json")
    by_year = supply.summarise(supply.run()).set_index("year").energized_gw.to_dict()
    reports = {
        "tam_ladder": demand.tam_ladder(),
        "capital_by_buyer": demand.capital_by_buyer(),
        "consumption_split": demand.consumption_split(),
        "demand_measure_reconciliation": demand.demand_measure_reconciliation(supply.p),
        "serviceable_demand": demand.serviceable(by_year),
        "capital_service_cohorts": demand.capital_cohorts(),
        "capital_supply_diagnostic": pd.DataFrame([demand.cross_check(by_year[demand.reference_year])]),
    }
    mix_reports, impacts = [], []
    for scenario in [*demand.p.get("customer_segment_mix.terminal_shares"), "static-control"]:
        model = DemandModel(demand.p, mix_scenario=scenario)
        mix_reports.append(model.customer_segment_mix())
        impacts.append(model.segment_mix_impact(by_year))
    reports["customer_segment_mix"] = pd.concat(mix_reports,ignore_index=True)
    impact = pd.concat(impacts,ignore_index=True)
    control = impact[impact.scenario == "static-control"].set_index("year")
    for key in ("merchant_requested_service_gw", "deferred_gw", "annualized_revenue_opportunity_usd_bn",
                "ready_capacity_occupancy_ratio"):
        impact["delta_vs_static_"+key] = impact[key]-impact.year.map(control[key])
    reports["segment_mix_impact"] = impact
    sensitivities=[]
    original = json.loads((HERE / "demand_parameters.json").read_text(encoding="utf-8"))
    for cost in demand.p.get("model.capex_sensitivity"):
        for us_share in demand.p.get("model.geography_sensitivity"):
            blob=deepcopy(original)
            blob["unit_economics"]["capex_per_gw_usd_bn"]["value"]=cost
            blob["model"]["us_capacity_share"]["value"]=us_share
            frame=DemandModel(Params(blob)).serviceable(by_year)
            sensitivities.append(dict(capex_per_gw_usd_bn=cost,us_capacity_share=us_share,
                occupied_gw=frame.occupied_additions_gw.sum(),ending_deferred_gw=frame.deferred_gw.iloc[-1],
                ending_spare_ready_gw=frame.available_ready_end_gw.iloc[-1]))
    reports["merchant_sensitivity"] = pd.DataFrame(sensitivities)
    reports['demand_parameter_registry'] = pd.DataFrame(demand.p.registry())
    for name,frame in reports.items():
        frame.to_csv(out / f"{name}.csv",index=False)
    comparison=supply.demand_vs_supply(supply.run())
    service=reports['serviceable_demand']
    lines=['# Generated base scenario', '', 'Generated by `run_demand.py` from the canonical registries. These are conditional scenarios, not observed deliveries or validated forecasts.', '',
           '| Year | US energized additions GW | US requested service, bookings base GW | Supply minus service GW | Merchant unmet GW | Merchant spare ready GW |',
           '|---|---|---|---|---|---|']
    for row, merchant in zip(comparison.itertuples(),service.itertuples()):
        lines.append(f'| {row.year} | {row.energized_gw:.2f} | {row.required_service_base_gw:.2f} | {row.gap_vs_base_gw:.2f} | {merchant.deferred_gw:.2f} | {merchant.available_ready_end_gw:.2f} |')
    cleared=service.loc[service.deferred_gw==0,'year']
    lines += ['',f'Merchant backlog first clears in {int(cleared.iloc[0]) if len(cleared) else "no year in this window"}. Ending spare ready capacity is {service.available_ready_end_gw.iloc[-1]:.2f} GW. This contrary output is retained.', '',
              'The bookings and merchant capital lenses are not summed or forced to agree. The low booking-growth scenario also permits supply to exceed requested service; inspect `demand_vs_supply.csv`.', '',
              f'The former {supply.p.get("validation.cbre_primary_inventory_2025_gw")} GW historical benchmark is inventory stock and is excluded from delivery validation. Actual live IT electrical load is not estimated. Occupied capacity is a modeled matching proxy.']
    lines += ["", "## Customer funding mix scenarios", "",
              "All segment paths are assumed; interpolation and impacts are derived. Total capital growth and supply are held fixed. Provider spend is capital investment; revenue is an occupied-capacity annual run-rate opportunity, not recognized sales.", "",
              "| Scenario | Backlog first clears | Ready additions first cover new requests | Ending spare GW | Ending occupancy of ready capacity | Ending revenue opportunity $bn/year |",
              "|---|---|---|---|---|---|"]
    for scenario, f in impact.groupby("scenario",sort=False):
        clear = f.loc[f.deferred_gw <= 1e-9,"year"]
        cross = f.loc[f.ready_additions_minus_requested_gw >= -1e-9,"year"]
        last = f.iloc[-1]
        lines.append(f"| {scenario} | {int(clear.iloc[0]) if len(clear) else 'None in window'} | {int(cross.iloc[0]) if len(cross) else 'None in window'} | {last.available_ready_end_gw:.2f} | {last.ready_capacity_occupancy_ratio:.1%} | {last.annualized_revenue_opportunity_usd_bn:.2f} |")
    lines += ["", "Crossover above compares annual merchant ready additions with new merchant requested service, excluding prior backlog. Backlog clearance includes carryover. First crossing need not be permanent; inspect annual CSVs. The separate all-market bookings/supply crossover is unchanged by funding mix."]
    (out/'results.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(reports["serviceable_demand"].to_string(index=False))
    print("\nUS geography, supply ownership and ramp are assumptions. Revenue is an annual run-rate opportunity, not recognized sales.")


if __name__ == "__main__":
    main()
